version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - .env
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    command: npm start:dev

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
